name: End-to-end tests
on: 
  workflow_dispatch:
jobs:
  cypress-tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # run 3 copies of the current job in parallel
        containers: [1, 2, 3]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Install Currents
      - name: Install packages
        run: npm i

      # Run all Cypress tests
      - name: Run Cypress on Currents.dev
        uses: cypress-io/github-action@v2
        with:
          command: npm cy2 run --record --parallel --key none --ci-build-id "${{ github.repository }}-${{ github.run_id }}-${{ github.run_attempt}}"