name: End-to-end tests
on: 
  workflow_dispatch:
jobs:
  cypress-tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # run 3 copies of the current job in parallel
        containers: [1, 2, 3]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run Docker
        run: docker run -p 1234:1234 agoldis/sorry-cypress-director

      - name: Install packages
        run: npm i

      # Run all Cypress tests
      - name: Run Cypress tests
        uses: cypress-io/github-action@v2
        with:
          command: export CYPRESS_API_URL="http://localhost:1234/" && CYPRESS_API_URL="http://localhost:1234/" npx cy2 run --parallel --record --key somekey --ci-build-id "${{ github.repository }}-${{ github.run_id }}-${{ github.run_attempt}}"