name: Parallel Cypress Tests from Cy Real App
# https://github.com/cypress-io/cypress-realworld-app/blob/develop/.github/workflows/main.yml

on:
  workflow_dispatch:

jobs:
  configure:
    runs-on: ubuntu-latest
    outputs:
      uid_gid: ${{ steps.get-user.outputs.uid_gid }}
    steps:
      - id: get-user
        run: echo "::set-output name=uid_gid::$(id -u):$(id -g)"

  install-packages-run-tests:
    needs: configure
    runs-on: ubuntu-latest
    container:
      image: agoldis/sorry-cypress-director
      options: --user ${{ needs.configure.outputs.uid_gid }} -p 1234:1234
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          docker exec -u root -t -i container_id /bin/bash
          apt-get install -y libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb
      - name: Install packages
        run: |
          npm install
          cd $PWD
          ls node_modules
      # - name: Run tests
      #   run: |
      #     export CYPRESS_API_URL="http://localhost:1234/"
      #     CYPRESS_API_URL="http://localhost:1234/" npx cy2 run --parallel --record --key somekey --ci-build-id hello-cypress
