name: Parallel Cypress Tests from Cy Real App
# https://github.com/cypress-io/cypress-realworld-app/blob/develop/.github/workflows/main.yml

on:
  workflow_dispatch:

jobs:
  configure:
    runs-on: ubuntu-latest
    outputs:
      uid_gid: ${{ steps.get-user.outputs.uid_gid }}
    steps:
      - id: get-user
        run: echo "::set-output name=uid_gid::$(id -u):$(id -g)"

  clone-and-install:
    needs: configure
    runs-on: ubuntu-latest
    container:
      image: agoldis/sorry-cypress-director
      options: --user ${{ needs.configure.outputs.uid_gid }}
    steps:
      - uses: actions/checkout@v2
      # - uses: bahmutov/npm-install@v1
      - name: Run tests
        run: |
          npm install
          cd $PWD
          export CYPRESS_API_URL="http://localhost:1234/"
          npx cy2 run --record --key XXX --parallel --ci-build-id `date +%s`
          CYPRESS_API_URL="http://localhost:1234/" npx cy2 run --browser chrome --parallel --record --key somekey --ci-build-id hello-cypress




# ls -al
# ls node_modules/