name: Parallel Cypress Tests from Cy Real App
# https://github.com/cypress-io/cypress-realworld-app/blob/develop/.github/workflows/main.yml

on:
  workflow_dispatch:

# permissions:
#   id-token: write
#   contents: read    # This is required for actions/checkout@v2

# jobs:
#   install:
#     runs-on: ubuntu-18.04
#     container: agoldis/sorry-cypress-director
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v2

#       - name: Cypress install
#         uses: cypress-io/github-action@v2
#         with:
#           runTests: false
#       # report machine parameters
#       - run: npx cypress info

jobs:
  configure:
    runs-on: ubuntu-latest
    outputs:
      uid_gid: ${{ steps.get-user.outputs.uid_gid }}
    steps:
      - id: get-user
        run: echo "::set-output name=uid_gid::$(id -u):$(id -g)"

  clone-and-install:
    needs: configure
    runs-on: ubuntu-latest
    container:
      image: agoldis/sorry-cypress-director
      options: --user ${{ needs.configure.outputs.uid_gid }}
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: |
          npm i
          ls -al