name: Parallel Cypress Tests from Cy Real App
# https://github.com/cypress-io/cypress-realworld-app/blob/develop/.github/workflows/main.yml

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read    # This is required for actions/checkout@v2

jobs:
  install:
    runs-on: ubuntu-latest
    container: agoldis/sorry-cypress-director
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cypress install
        uses: cypress-io/github-action@v2
        with:
          runTests: false
      # report machine parameters
      - run: npx cypress info
