name: Parallel Cypress Tests from Cy Real App
# https://github.com/cypress-io/cypress-realworld-app/blob/develop/.github/workflows/main.yml

on:
  workflow_dispatch:

jobs:
  configure:
    runs-on: ubuntu-latest
    outputs:
      uid_gid: ${{ steps.get-user.outputs.uid_gid }}
    steps:
      - id: get-user
        run: echo "::set-output name=uid_gid::$(id -u):$(id -g)"

  clone-and-install:
    needs: configure
    runs-on: ubuntu-latest
    container:
      image: agoldis/sorry-cypress-director
      options: --user ${{ needs.configure.outputs.uid_gid }}
    steps:
      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Run tests
        run: |
          npm i
          ls -al