name: Parallel Cypress Tests - sequenial
# https://github.com/cypress-io/cypress-realworld-app/blob/develop/.github/workflows/main.yml

on:
  workflow_dispatch:

jobs:
  configure:
    runs-on: macos-11
    outputs:
      uid_gid: ${{ steps.get-user.outputs.uid_gid }}
    steps:
      - id: get-user
        run: echo "::set-output name=uid_gid::$(id -u):$(id -g)"

  install-packages-run-tests:
    needs: configure
    runs-on: macos-11
    container:
      image: agoldis/sorry-cypress-director
      options: --user ${{ needs.configure.outputs.uid_gid }}
    steps:
      - uses: actions/checkout@v2
      - run: |
          npm i
          npx cypress run
