name: Parallel Cypress Tests

on:
  workflow_dispatch:

jobs:
  data-checks:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Set the value
        id: step_one
        run: |
          node create-env-var.js
          echo "PERCY_TOKEN=$(cat temptokens.txt)" >> $GITHUB_ENV
        env:
          PUBLICATION_UNDER_TEST: ${{ github.event.inputs.envUnderTest }}

      - name: Use the value
        id: step_two
        run: |
          echo "${{ env.PERCY_TOKEN }}"

# jobs:
#   parallel-test-running:
#     runs-on: ubuntu-latest
#     # container:
#     #   image: agoldis/sorry-cypress-director
#     #   ports:
#     #     - 1234:1234
#     # strategy:
#     #   fail-fast: false
#     #   matrix:
#     #     containers: [1, 2, 3]

#     steps:
#       - uses: actions/checkout@v2

#       - name: Install packages
#         run: |
#           npm i

#       - name: Run tests
#           export CYPRESS_API_URL="http://localhost:1234/"
#           npx cy2 run --record --key XXX --parallel --ci-build-id `date +%s`
#           CYPRESS_API_URL="http://localhost:1234/" npx cy2 run --browser chrome --parallel --record --key somekey --ci-build-id hello-cypress
