name: Parallel Cypress Tests

on:
  workflow_dispatch:
    inputs:
      envUnderTest:
        description: "Select environment to run tests against."
        required: true
        default: "https://www.google.co.uk"

jobs:
  parallel-cypress:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Show inputs
        run: |
          echo "branch: ${GITHUB_REF##*/}"
