name: Parallel Cypress Tests

on:
  workflow_dispatch:

jobs:
  parallel-cypress:
    runs-on: ubuntu-latest
    container:
        image: agoldis/sorry-cypress-director
        ports:
          - 1234:1234
    # strategy:
    #   fail-fast: false
    #   matrix:
    #     containers: [1, 2, 3]

    steps:
      - uses: actions/checkout@v2

      - name: Show inputs
        run: |
          echo "branch: ${GITHUB_REF##*/}"

      - name: Curl director
        run: |
          curl http://localhost:1234

      # - name: Run tests
      #   run: |
      #     npm i
      #     export CYPRESS_API_URL="http://localhost:1234/"
      #     npx cy2 run --record --key XXX --parallel --ci-build-id `date +%s`
      #     CYPRESS_API_URL="http://localhost:1234/" npx cy2 run --browser chrome --parallel --record --key somekey --ci-build-id hello-cypress

