name: Parallel Cypress Tests

on:
  workflow_dispatch:
    inputs:
      envUnderTest:
        description: "Select environment to run tests against."
        required: true
        default: "https://www.google.co.uk"

jobs:
  parallel-cypress:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Show inputs
        run: |
          echo "branch: ${GITHUB_REF##*/}"

      - name: Run tests
        run: |
          export CYPRESS_API_URL="http://localhost:1234/"
          npx cy2 run --record --key XXX --parallel --ci-build-id `date +%s`
          CYPRESS_API_URL="http://localhost:1234/" npx cy2 run --browser chrome --parallel --record --key somekey --ci-build-id hello-cypress

